# Generated by Django 5.1.7 on 2025-03-20 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statvalue',
            name='refresh',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 20, 21, 23, 2, 906618)),
        ),
    ]
