# Generated by Django 5.1.7 on 2025-03-20 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_statvalue_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statvalue',
            name='refresh',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
