# Generated by Django 5.1.7 on 2025-03-20 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_statvalue_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statvalue',
            name='refresh',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='statvalue',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
