# Generated by Django 5.1.7 on 2025-03-20 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_statvalue_refresh_alter_statvalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statvalue',
            name='refresh',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
