# Generated by Django 5.1.7 on 2025-03-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_alter_statvalue_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statvalue',
            name='refresh',
        ),
    ]
