# Generated by Django 5.1.7 on 2025-03-22 13:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_remove_statvalue_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='statvalue',
            name='refresh',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
