# Generated by Django 5.1.7 on 2025-03-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_statvalue_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statvalue',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
