# Generated by Django 5.1.7 on 2025-03-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_achievement_achievementstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='displayname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stat',
            name='displayname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
