# Generated by Django 5.1.7 on 2025-03-25 09:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('tracking', '0011_alter_statvalue_value_instancecompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(blank=True, default=0, null=True)),
                ('refresh', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
