# Generated by Django 5.1.7 on 2025-03-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='uid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
