# Generated by Django 5.1.7 on 2025-03-14 13:32

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'slug'], name='games_compa_name_b4ae5b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'])),
            ],
            options={
                'indexes': [models.Index(fields=['name', 'slug'], name='games_tag_name_08848a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('aliases', models.JSONField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, db_index=True, null=True)),
                ('cover', models.URLField(blank=True, null=True)),
                ('companies', models.ManyToManyField(db_index=True, to='games.company')),
                ('tags', models.ManyToManyField(db_index=True, to='games.tag')),
            ],
        ),
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_instances', to='games.game')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platform')),
            ],
            options={
                'unique_together': {('game', 'platform')},
            },
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name', 'popularity'], name='games_game_name_21a62a_idx'),
        ),
    ]
